print("hi")
import os
def clear_screen():
    os.system('clear')

import time
clear_screen()
print("Welcome adventurer to this wonderful land")
time.sleep(3)
clear_screen()
print("Of wonder and whimsy")
time.sleep(3)
clear_screen()
print("And...")
time.sleep(2)
print("Ducks??")
time.sleep(2)
clear_screen()
print("##############")
time.sleep(0.5)
print("#            #")
time.sleep(0.5)
print("#   DUCKS    #")
time.sleep(0.5)
print("#            #")
time.sleep(0.5)
print("#            #")
time.sleep(0.5)
print("#            #")
time.sleep(0.5)
print("#            #")
time.sleep(0.5)
print("##############")
time.sleep(2)
clear_screen()
print("##############")
print("#            #")
print("#           <#")
print("#           (#")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(1)
clear_screen()
print("##############")
print("#            #")
print("#          <'#")
print("#          ( #")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(1)
clear_screen()
print("##############")
print("#            #")
print("#         <')#")
print("#         (  #")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(1)
clear_screen()
print("##############")
print("#            #")
print("#        <')_#")
print("#        (  >#")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(1)
clear_screen()
print("##############")
print("#            #")
print("#       <')__#")
print("#       (  > #")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(1)
clear_screen()
print("##############")
print("#            #")
print("#      <')__.#")
print("#      (  > )#")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(1)
clear_screen()
print("##############")
print("#            #")
print("#     <')__. #")
print("#     (  > ) #")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(5)
clear_screen()
print("##############")
print("#    ___     #")
print("#   ('<')__. #")
print("#    (  > )  #")
print("#            #")
print("#            #")
print("#     ^      #")
print("##############")
time.sleep(3)
clear_screen()
print("##############")
print("#    ___     #")
print("#   ('<')__. #")
print("#    (  > )  #")
print("#            #")
print("#    RUN     #")
print("#     ^      #")
print("##############")
time.sleep(5)
clear_screen()
print("##############")
print("#            #")
print("#    ___     #")
print("#   ('<')__. #")
print("#    (  > )  #")
print("#            #")
print("#     ^  RUN!#")
print("##############")
time.sleep(5)
clear_screen()
print("##############")
print("#            #")
print("#    RUN!!   #")
print("#    ___     #")
print("#   ('<')__. #")
print("#    (  > )  #")
print("#     ^      #")
print("##############")
time.sleep(5)
clear_screen()
print("You got chomped")
time.sleep(3)
clear_screen()
print("fool")
